name: Build docs

on:
  push:
    # branches:
    #   - main
  pull_request:

env:
  vessel_version: "v0.6.3"
  moc_version: "0.5.14"
  dfx_version: "0.9.3"
  node_version: "17"

jobs:
  tests:
    # if: github.ref != 'refs/heads/next-moc' && github.base_ref != 'refs/heads/next-moc'
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Check if Git tag exists
      run: echo "name=HEAD_TAG::$(git tag --points-at HEAD)" >> $GITHUB_ENV
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-20.09
    - name: "install dependencies"
      run: |
        nix-env --install wasmtime --file '<nixpkgs>'
        nix-env --install graphviz --file '<nixpkgs>'
    - name: "install Motoko binaries"
      run: |
       wget https://download.dfinity.systems/motoko/${{ env.moc_version }}/x86_64-linux/motoko-${{ env.moc_version }}.tar.gz
       mkdir -p /home/runner/bin
       tar -xf motoko-${{ env.moc_version }}.tar.gz -C /home/runner/bin
       echo "/home/runner/bin" >> $GITHUB_PATH
    - name: "install vessel"
      run: |
       wget --output-document /home/runner/bin/vessel https://github.com/kritzcreek/vessel/releases/download/${{ env.vessel_version }}/vessel-linux64
       chmod +x /home/runner/bin/vessel
    - name: "docs"
      # if: github.ref != 'refs/heads/next-moc' && github.base_ref != 'refs/heads/next-moc'
      run: |
        pushd doc
        mo-doc --source ../canister/lib --output modules/base-libraries/pages/ --format adoc
        popd
    - name: Upload docs
      uses: JamesIves/github-pages-deploy-action@releases/v3
      if: github.ref == 'refs/heads/master'
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: doc-pages
        FOLDER: doc/