name: Build docs

on:
  push:
    # branches:
      # - main

jobs:
  docs:
    # if: github.ref != 'refs/heads/next-moc' && github.base_ref != 'refs/heads/next-moc'
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: aviate-labs/setup-dfx@v0.2.3
      with:
        dfx-version: 0.9.3
        vessel-version: 0.6.3
    # - name: Check if Git tag exists
    #   run: echo "name=HEAD_TAG::$(git tag --points-at HEAD)" >> $GITHUB_ENV
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-20.09
    - name: "install Motoko binaries"
      run: |
       wget https://download.dfinity.systems/motoko/${{ env.moc_version }}/x86_64-linux/motoko-${{ env.moc_version }}.tar.gz
       mkdir -p /home/runner/bin
       tar -xf motoko-${{ env.moc_version }}.tar.gz -C /home/runner/bin
       echo "/home/runner/bin" >> $GITHUB_PATH
    - name: "docs"
      # if: github.ref != 'refs/heads/next-moc' && github.base_ref != 'refs/heads/next-moc'
      run: |
        pushd canister/doc
        mo-doc --source ../lib --output modules/base-libraries/pages/ --format adoc
        popd
    - name: Upload docs
      uses: JamesIves/github-pages-deploy-action@releases/v3
      # if: github.ref == 'refs/heads/main'
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: doc-pages
        FOLDER: canister/doc/